### ISSUE TITLE
coroutil-1.10.2-1.1.7 - Breaks /help command

### ISSUE THREAD

**Issue by ktole1999** [Corosauce/CoroUtil#14]
when this mod is not in on server help works just fine. with this mod the help command gives java.util.NoSuchElementException.

forge-1.10.2-12.18.1.2052-universal
spongeforge-1.10.2-2052-5.0.0-BETA-1675

-----------------------------------------
[10:15:29] [Server thread/INFO]: Error occurred while executing command: null
[10:15:29] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'help' for source DedicatedServer: null
java.util.NoSuchElementException
        at org.spongepowered.common.text.TextComponentIterator.next(TextComponentIterator.java:61) ~[TextComponentIterator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.text.TextComponentIterator.next(TextComponentIterator.java:38) ~[TextComponentIterator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.text.TextComponentIterator.next(TextComponentIterator.java:73) ~[TextComponentIterator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.text.TextComponentIterator.next(TextComponentIterator.java:38) ~[TextComponentIterator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.service.pagination.PaginationCalculator.getWidth(PaginationCalculator.java:149) ~[PaginationCalculator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.service.pagination.PaginationCalculator.getLines(PaginationCalculator.java:99) ~[PaginationCalculator.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.service.pagination.SpongePaginationList.lambda$sendTo$0(SpongePaginationList.java:108) ~[SpongePaginationList.class:1.10.2-2052-5.0.0-BETA-1675]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_101]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_101]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_101]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_101]
        at org.spongepowered.common.service.pagination.SpongePaginationList.sendTo(SpongePaginationList.java:110) ~[SpongePaginationList.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.service.pagination.SpongePaginationBuilder.sendTo(SpongePaginationBuilder.java:112) ~[SpongePaginationBuilder.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.command.SpongeHelpCommand.lambda$create$3(SpongeHelpCommand.java:86) ~[SpongeHelpCommand.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2052-5.0.0-BETA-1675]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-2052-5.0.0-BETA-1675]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by ktole1999** [comment]
without sponge i get this error running strictly forge:

[10:20:17] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeLo(Unknown Source) ~[?:1.8.0_101]
        at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.8.0_101]
        at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:1.8.0_101]
        at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.8.0_101]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_101]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_101]
        at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_101]
        at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_101]
        at net.minecraft.command.CommandHelp.func_184900_a(SourceFile:118) ~[al.class:?]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:73) ~[al.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Oxosorrel** [comment]
Not the dev, but try https://minecraft.curseforge.com/projects/helpfixer it's a server side mod that underps forge and /help commands being implemented by mods. It worked for my server, on other mods, but your mileage may vary.

**Comment by ktole1999** [comment]
help fixer did not resolve. IoP from ftb irc room already suggested that. But thanks for the tip.

**Comment by Corosauce** [comment]
Strange, I don't even touch the /help command, I just have a /config /coroutil and /coroutilc for client side

**Comment by Corosauce** [comment]
According to the guys over at #spongedev it is a bug in sponge itself, leaving it with them as they are looking into it, will keep this ticket open for a bit.

**Comment by Corosauce** [comment]
A couple of commits have been pushed to SpongeCommon to fix this, latest commit is https://github.com/SpongePowered/SpongeCommon/compare/310edeff55dc...85d7913dbb30
