### ISSUE TITLE
Crash on server with latest release version for 1.12.2

### ISSUE THREAD

**Issue by GordonHollow** [Corosauce/CoroUtil#24]
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at CoroUtil.world.WorldDirector.tick(WorldDirector.java:219)
	at CoroUtil.world.WorldDirectorManager.onTick(WorldDirectorManager.java:172)
	at CoroUtil.forge.EventHandlerFML.tickServer(EventHandlerFML.java:67)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2153_EventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Corosauce** [comment]
Fixed in dev and a new build out to curse.
