### ISSUE TITLE
Crash when placing the Repairing Block Repeatly (coroutil 1.2.3)

### ISSUE THREAD

**Issue by TornadoChasing123** [Corosauce/CoroUtil#26]
What happen here is when I'm placing the Repairing Block, the game crashes.
Here's the part of the log file and the crash report:

[15:05:03] [main/INFO]: [CHAT] Operation completed (1115 blocks affected).
[15:05:25] [main/INFO]: [CHAT] Unknown command. Try /help for a list of commands
[15:05:29] [main/INFO]: [CHAT] Undo successful.
[15:05:35] [main/INFO]: [CHAT] Second position set to (-437.0, 54.0, 653.0) (11622).
[15:05:38] [Server thread/INFO]: puppy has made the advancement [Diamonds!]
[15:05:38] [main/INFO]: [CHAT] puppy has made the advancement [Diamonds!]
[15:05:40] [main/INFO]: [CHAT] Operation completed (903 blocks affected).
[15:07:06] [Server thread/INFO]: username has made the advancement [Diamonds!]
[15:07:06] [main/INFO]: [CHAT] username has made the advancement [Diamonds!]
[15:07:06] [main/INFO]: Loaded 44 advancements
[15:07:10] [main/INFO]: Loaded 46 advancements
[15:07:22] [Server thread/INFO]: <username> STOP IT PLS
[15:07:22] [main/INFO]: [CHAT] <username> STOP IT PLS
[15:08:30] [main/INFO]: [CHAT] First position set to (-399.0, 55.0, 505.0) (11622).
[15:08:35] [main/INFO]: [CHAT] Second position set to (-437.0, 55.0, 553.0) (1911).
[15:08:38] [main/INFO]: [CHAT] Operation completed (0 blocks affected).
[15:11:19] [Server thread/INFO]: [username: Set the time to 0]
[15:11:19] [main/INFO]: [CHAT] Set the time to 0
[15:13:10] [main/INFO]: [CHAT] puppy, username
[15:13:10] [main/INFO]: [CHAT] puppy, username
[15:13:11] [main/INFO]: [CHAT] puppy, username
[15:13:12] [Server thread/INFO]: [username: Teleported username to puppy]
[15:13:12] [main/INFO]: [CHAT] Teleported username to puppy
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [Server thread/INFO]: [username: Killed Sheep]
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:15:07] [main/INFO]: [CHAT] Killed Sheep
[15:17:18] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -469 Y: 61 Z: 555 to monitor.
[15:17:19] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -472 Y: 61 Z: 555 to monitor.
[15:17:21] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:17:23] [Server thread/INFO]: puppy has made the advancement [Stone Age]
[15:17:23] [main/INFO]: [CHAT] puppy has made the advancement [Stone Age]
[15:17:52] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:18:59] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:19:19] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:19:53] [main/INFO]: [CHAT] [§cUniversal Owner Changer§f] You need to give this item the name of the new block owner. Use an anvil to rename it.
[15:20:21] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:21:26] [main/INFO]: Loaded 47 advancements
[15:22:19] [Server thread/INFO]: [username: Set the time to 0]
[15:22:19] [main/INFO]: [CHAT] Set the time to 0
[15:23:05] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -459 Y: 61 Z: 557 to monitor.
[15:23:07] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -457 Y: 61 Z: 557 to monitor.
[15:23:58] [main/INFO]: [CHAT] [§cCamera Monitor§f] Unbound camera at X: -472 Y: 61 Z: 555 from monitor.
[15:24:04] [main/INFO]: [CHAT] [§cCamera Monitor§f] Unbound camera at X: -457 Y: 61 Z: 557 from monitor.
[15:24:27] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -462 Y: 65 Z: 494 to monitor.
[15:24:28] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -463 Y: 65 Z: 495 to monitor.
[15:24:28] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -462 Y: 65 Z: 496 to monitor.
[15:24:29] [main/INFO]: [CHAT] [§aCamera Monitor§f] Bound camera at X: -461 Y: 65 Z: 495 to monitor.
[15:24:36] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:24:41] [main/INFO]: [CHAT] [§aSecurity Camera§f] You are now mounted to a camera. Use the WASD keys to move the camera's view, and the +/- buttons to zoom in and out.
[15:25:25] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at CoroUtil.block.TileEntityRepairingBlock.func_189515_b(TileEntityRepairingBlock.java:91) ~[TileEntityRepairingBlock.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:335) ~[amu.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180) ~[ahb.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[ahb.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:860) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[15:25:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at CoroUtil.block.TileEntityRepairingBlock.func_189515_b(TileEntityRepairingBlock.java:91) ~[TileEntityRepairingBlock.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:335) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:424) ~[amu.class:?]
	at CoroUtil.block.TileEntityRepairingBlock.func_73660_a(TileEntityRepairingBlock.java:40) ~[TileEntityRepairingBlock.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[15:25:27] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Administrator\AppData\Roaming\.minecraft\1.12.2(2)\crash-reports\crash-2018-05-05_15.25.25-server.txt
[15:25:27] [Server thread/INFO]: Stopping server
[15:25:27] [Server thread/INFO]: Saving players
[15:25:27] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModMain (lda-0.1.1-corePlugin.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/5/18 3:25 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at CoroUtil.block.TileEntityRepairingBlock.func_189515_b(TileEntityRepairingBlock.java:91)
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82)
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175656_a(World.java:424)
	at CoroUtil.block.TileEntityRepairingBlock.func_73660_a(TileEntityRepairingBlock.java:40)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at CoroUtil.block.TileEntityRepairingBlock.func_189515_b(TileEntityRepairingBlock.java:91)
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82)
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175656_a(World.java:424)
	at CoroUtil.block.TileEntityRepairingBlock.func_73660_a(TileEntityRepairingBlock.java:40)

-- Block entity being ticked --
Details:
	Name: minecraft:repairing_block // CoroUtil.block.TileEntityRepairingBlock
	Block type: ID #395 (tile.coroutil.repairing_block // CoroUtil.block.BlockRepairingBlock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-432,55,510), Chunk: (at 0,3,14 in -27,31; contains blocks -432,0,496 to -417,255,511), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #395 (tile.coroutil.repairing_block // CoroUtil.block.BlockRepairingBlock)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: City
	All players: 2 total; [EntityPlayerMP['username'/155713, l='City', x=-432.30, y=57.53, z=512.54], EntityPlayerMP['puppy'/155777, l='City', x=-400.34, y=55.00, z=518.16]]
	Chunk stats: ServerChunkCache: 370 Drop: 0
	Level seed: 3928100706749102686
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,50*minecraft:stone,3*minecraft:dirt,minecraft:grass;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
	Level spawn location: World: (-479,4,562), Chunk: (at 1,0,2 in -30,35; contains blocks -480,0,560 to -465,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 161140 game time, 3723 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6552 (now: true), thunder time: 17527 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 228437880 bytes (217 MB) / 1349779456 bytes (1287 MB) up to 1349779456 bytes (1287 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1299M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 Optifine OptiFine_1.12.2_HD_U_D1 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State                                        | ID                                           | Version           | Source                                        | Signature                                |
	|:-------------------------------------------- |:-------------------------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | minecraft                                    | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | mcp                                          | 9.42              | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | forge                                        | 14.23.2.2624      | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | securitycraft                                | v1.8.4.1          | [1.12.x]+SecurityCraft+v1.8.4.1.jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | codechickenlib                               | 3.1.5.331         | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | extendedrenderer                             | v1.0              | coroutil-1.12.1-1.2.5.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | coroutil                                     | 1.12.1-1.2.3      | coroutil-1.12.1-1.2.5.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | configmod                                    | v1.0              | coroutil-1.12.1-1.2.5.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | cdm                                          | 0.2.1             | device-mod-0.2.1-1.12.2.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | cfm                                          | 4.1.5             | furniture-4.1.5-1.12.2.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | waila                                        | 1.8.22            | Hwyla-1.8.22-B37_1.12.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | ironchest                                    | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | jei                                          | 4.8.5.143         | jei_1.12.2-4.8.5.143.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | lda                                          | 0.1.0             | lda-0.1.1.jar                                 | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | personalcars                                 | 1.4               | PersonalCars-1.4 (1).jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | rcroads                                      | 0.2.1             | RC-Roads-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | thutcore                                     | 5.15.1            | ThutCore-1.12.2 (1).jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | thutcore_compat                              | 1.0               | ThutCore-1.12.2 (1).jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | thuttech                                     | 6.0.11            | thuttech-1.12.2-6.0.11.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | wailaharvestability                          | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | wawla                                        | 2.5.247           | Wawla-1.12.2-2.5.247.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | weather2                                     | 1.12.1-2.6.4      | weather2-1.12.1-2.6.4.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | worldedit                                    | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | xaerominimap                                 | 1.14.8            | Xaeros_Minimap_1.14.8_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
CoreModMain (lda-0.1.1-corePlugin.jar)
  io.github.lukas2005.DeviceModApps.coremod.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['username'/155713, l='City', x=-432.30, y=57.53, z=512.54], EntityPlayerMP['puppy'/155777, l='City', x=-400.34, y=55.00, z=518.16]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4463
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
[15:25:27] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Administrator\AppData\Roaming\.minecraft\1.12.2(2)\crash-reports\crash-2018-05-05_15.25.25-server.txt
[15:25:27] [main/INFO] [FML]: Waiting for the server to terminate/save.
[15:25:27] [Server thread/INFO]: Saving worlds
[15:25:27] [Server thread/INFO]: Saving chunks for level 'City'/overworld
[15:25:27] [Server thread/ERROR] [FML]: A TileEntity type CoroUtil.block.TileEntityRepairingBlock has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
	at CoroUtil.block.TileEntityRepairingBlock.func_189515_b(TileEntityRepairingBlock.java:91) ~[TileEntityRepairingBlock.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:337) [chd.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:476) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:577) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[15:25:27] [Server thread/INFO]: Saving chunks for level 'City'/the_nether
[15:25:27] [Server thread/INFO]: Saving chunks for level 'City'/the_end
[15:25:27] [Server thread/INFO] [FML]: Unloading dimension 0
[15:25:27] [Server thread/INFO] [FML]: Unloading dimension -1
[15:25:27] [Server thread/INFO] [FML]: Unloading dimension 1
[15:25:27] [Server thread/INFO] [FML]: Applying holder lookups
[15:25:27] [Server thread/INFO] [FML]: Holder lookups applied
[15:25:27] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:25:27] [main/INFO] [FML]: Server terminated.
[15:25:27] [Client Shutdown Thread/INFO]: Stopping server
[15:25:27] [Client Shutdown Thread/INFO]: Saving players
[15:25:27] [Client Shutdown Thread/INFO]: username lost connection: Server closed
[15:25:27] [Client Shutdown Thread/INFO]: username left the game
[15:25:27] [Client Shutdown Thread/INFO]: Stopping singleplayer server as player logged out
[15:25:27] [Client Shutdown Thread/INFO]: Saving worlds
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Corosauce** [comment]
Thanks for testing, gotta make it a bit more resilient to broken data. In the meantime avoid using it until a new release is out.
