### ISSUE TITLE
Another log spam

### ISSUE THREAD

**Issue by Voidi** [Corosauce/CoroUtil#4]
`java.lang.ArrayIndexOutOfBoundsException: -1
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:511)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at CoroUtil.world.grid.chunk.ChunkDataPoint.initFirstTime(ChunkDataPoint.java:78)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at CoroUtil.world.grid.chunk.ChunkDataGrid.getChunkData(ChunkDataGrid.java:58)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at CoroUtil.world.grid.chunk.ChunkDataGrid.getChunkData(ChunkDataGrid.java:38)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at CoroUtil.forge.EventHandlerForge.blockPlayerInteract(EventHandlerForge.java:73)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler_388_EventHandlerForge_blockPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:140)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[11:52:53] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

and than a lot of java.lang.ArrayIndexOutOfBoundsException

**Comment by ajthemacboy** [comment]
Me too :(

**Comment by Corosauce** [comment]
Looks related to other issue posted, is now fixed in this commit https://github.com/Corosauce/CoroUtil/commit/8ca63707cf03a414722f4b56ba7e0cd5a597af18

Will push an update to site soon.
