### ISSUE TITLE
Rendering Overlay caused by CoroUtil Config

### ISSUE THREAD

**Issue by Daralexen05** [Corosauce/CoroUtil#58]
My game refuses to load know due to this on factor. I do not want to uninstall Zombie Awareness, because it is a major aspect of my modded hardcore world.

Report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 18/10/2023, 00:42
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.10-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.10-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2391!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?] {re:mixin}
-- MOD zombieawareness --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.10.jar%2393!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.10.jar%2392!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/jares/AppData/Roaming/.minecraft/mods/zombieawareness-1.18.1-1.12.3.jar
	Failure message: Zombie Awareness (zombieawareness) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.1-1.12.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
Stacktrace:
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?] {re:mixin}
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?] {re:mixin}
	at com.corosus.modconfig.ConfigMod.addConfigFile(ConfigMod.java:107) ~[coroutil-1.18.2-1.2.45.jar%2362!/:1.18.2-1.2.45] {re:classloading}
	at com.corosus.modconfig.ConfigMod.addConfigFile(ConfigMod.java:93) ~[coroutil-1.18.2-1.2.45.jar%2362!/:1.18.2-1.2.45] {re:classloading}
	at com.corosus.zombieawareness.ZombieAwareness.<init>(ZombieAwareness.java:49) ~[zombieawareness-1.18.1-1.12.3.jar%2389!/:1.18.1-1.12.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.10.jar%2393!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.10.jar%2392!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1042427440 bytes (994 MiB) / 1509949440 bytes (1440 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7530U with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon (TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x15e7
	Graphics card #0 versionInfo: DriverVersion=31.0.14058.5004
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Virtual memory max (MB): 19264.00
	Virtual memory used (MB): 10115.01
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 88.03
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		John_Mod_Reborn_1.0.3_mc1.18.2.jar                |John Mod Reborn               |john_mod_reborn               |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		mowziesmobs-1.5.32.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.32              |COMMON_SET|Manifest: NOSIGNATURE
		grimace-shake.jar                                 |grimace shake                 |grimace_shake                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Resident+Evil+Alpha+0.2.jar                       |Resident Evil                 |resident_evil                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		breakingbadmod1.1.4.jar                           |BreakingBadMod                |breakingbadmod                |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		zombiehorsespawn-1.18.2-4.6.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |4.6                 |COMMON_SET|Manifest: NOSIGNATURE
		1.18.2-enchantedgoldenapplecrafting-1.0.jar       |Enchanted Golden Apple Craftin|enchantedgoldenapplecrafting  |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		Glowing+Obsidian+1.18.2+vr-1.2.jar                |GlowIngObsidian               |glowingobsidian               |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		giantspawn-1.18.2-4.5.jar                         |Giant Spawn                   |giantspawn                    |4.5                 |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1005.jar                  |Just Enough Items             |jei                           |10.2.1.1005         |COMMON_SET|Manifest: NOSIGNATURE
		[FORGE]+Better+Ocelots+Version+1.0.0+For+1.18.2.ja|Better Ocelots                |betterocelots                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Zelda+Breath+of+the+Craft+Mod+v0.0.5+-+1.18.2.jar |Zelda Breath of the Craft Mod |botc                          |0.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		Satako-5.0.13-1.18.2.jar                          |Satako                        |satako                        |5.0.13-1.18.2       |COMMON_SET|Manifest: NOSIGNATURE
		guiclock-1.18.2-4.2.jar                           |GUI Clock                     |guiclock                      |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		rare_small_brick_pyramids.jar                     |Brick Pyramid                 |brick_pyramid                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.0      |COMMON_SET|Manifest: NOSIGNATURE
		klsts_metroid_mod_0.4.0.jar                       |Klsts' Metroid Mod            |klsts_metroid                 |0.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.2-6.65.jar                        |Collective                    |collective                    |6.65                |COMMON_SET|Manifest: NOSIGNATURE
		some-assembly-required-1.18.2-2.0.10.jar          |Some Assembly Required        |some_assembly_required        |1.18.2-2.0.10       |COMMON_SET|Manifest: NOSIGNATURE
		placeableitems-4.7.1.jar                          |Placeable Items               |placeableitems                |4.7.1               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |COMMON_SET|Manifest: NOSIGNATURE
		zombieawareness-1.18.1-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.18.1-1.12.3       |ERROR     |Manifest: NOSIGNATURE
		Atlas-Lib-1.18.2-1.1.7a.jar                       |Atlas Lib                     |atlaslib                      |1.1.7a              |COMMON_SET|Manifest: NOSIGNATURE
		coroutil-1.18.2-1.2.45.jar                        |CoroUtil                      |coroutil                      |1.18.2-1.2.45       |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.2.0-mc1.18.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		tyrannotitanlib-4.2.0.jar                         |Tyrannotitan Library          |tyrannotitanlib               |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		K-Turrets-1.1.21-1.18.2.jar                       |K-Turrets                     |k_turrets                     |1.1.21-1.18.2       |COMMON_SET|Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.18.2-2.0.7.jar        |Enhanced Celestials           |enhancedcelestials            |2.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		Craft-Vania-1.18.2-1.3.2.jar                      |Craft-Vania                   |craftvania2                   |1.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		FemaleVillagers-1.18.2-1.7a.jar                   |Female Villagers              |femalevillagers               |1.7a                |COMMON_SET|Manifest: NOSIGNATURE
		Paraglider-1.18.2-1.6.0.6.jar                     |Paraglider                    |paraglider                    |1.6.0.6             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.10-universal.jar                |Forge                         |forge                         |40.2.10             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mavm-forge-1.18.1-1.0.7a.jar                      |More Axolotl Variants Mod     |mavm                          |1.0.7a              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |COMMON_SET|Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.18.2-1.4.7.jar           |Friends&Foes                  |friendsandfoes                |1.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		armor-visibility-4.0.0-forge.jar                  |Armor Visibility              |armor_visibility              |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		domesticationinnovation-1.4.1-1.18.2.jar          |Domestication Innovation      |domesticationinnovation       |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 66c6929e-d21d-42fb-973d-aa17c8ea3601
	FML: 40.2
	Forge: net.minecraftforge:40.2.10

**Comment by Daralexen05** [comment]
It turns out that I just needed to delete all of my config files because I had a lot of leftover 1.12.2 config files from a mudpack.
