### ISSUE TITLE
crash in 1.21.1

### ISSUE THREAD

**Issue by eliyya** [Corosauce/CoroUtil#64]
**Describe the bug**
mod does not work in 1.21.1, crashes at startup

**To Reproduce**
1. download coroutils 1.21.0-1.3.7 in the mod folder of the fabric server
2. start the server
3. See error

**latest.log, debug.log or crash report if the other 2 arent possible**
```sh-session
[00:10:36] [main/WARN]: Reference map 'coroutil.refmap.json' for coroutil_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[00:10:36] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'coroutil' at 'com.corosus.coroutil.loader.fabric.ConfigModFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.3.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server_1.21.0_fabric_0.16.3_1.0.1.jar:1.0.1]
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'coroutil'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
        ... 7 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:60) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/config/IConfigSpec
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at com.corosus.coroutil.util.MultiLoaderUtil.constructLoaderSpecificConfigData(MultiLoaderUtil.java:77) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.coroutil.util.MultiLoaderUtil.makeLoaderSpecificConfigData(MultiLoaderUtil.java:67) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.CoroConfigRegistry.addConfigFile(CoroConfigRegistry.java:112) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.CoroConfigRegistry.addConfigFile(CoroConfigRegistry.java:95) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.ConfigMod.<init>(ConfigMod.java:21) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.coroutil.loader.fabric.ConfigModFabric.<init>(ConfigModFabric.java:13) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.config.IConfigSpec
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.3.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at com.corosus.coroutil.util.MultiLoaderUtil.constructLoaderSpecificConfigData(MultiLoaderUtil.java:77) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.coroutil.util.MultiLoaderUtil.makeLoaderSpecificConfigData(MultiLoaderUtil.java:67) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.CoroConfigRegistry.addConfigFile(CoroConfigRegistry.java:112) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.CoroConfigRegistry.addConfigFile(CoroConfigRegistry.java:95) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.modconfig.ConfigMod.<init>(ConfigMod.java:21) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at com.corosus.coroutil.loader.fabric.ConfigModFabric.<init>(ConfigModFabric.java:13) ~[coroutil-fabric-1.21.0-1.3.7.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:58) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.3.jar:?]
        ... 7 more
```

**Expected behavior**
was expected to start.

**Screenshots**

**Mod and Minecraft version:**
Without this your issue will likely get closed for lacking enough info.
 - Fabric server: 1.21.1-0.16.3
 - coroutils: 1.21.0-1.3.7

**Additional context**

**Comment by TheeMrCheeky** [comment]
hope all is well @eliyya just wondering if and when this may get fixed? really want to use zombie awareness in my MP but sadly can't :(

**Comment by eliyya** [comment]
> hope all is well [@eliyya](https://github.com/eliyya?rgh-link-date=2025-01-31T03%3A44%3A47.000Z) just wondering if and when this may get fixed? really want to use zombie awareness in my MP but sadly can't :(

Soon, when the new update comes out
